# THIS IS PREINSTALLED CONFIGURATION.YAML
# As a basis the default generated HA version is used and items are appended if the need to be activated

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Bypass login page if localhost
homeassistant:
  internal_url: "http://reterminal.local:8123"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant

# Add custom lovelace frontend
lovelace:
  mode: storage
  dashboards:
    # Main Dashboard
    ui-dashboard:
      require_admin: false
      show_in_sidebar: true
      icon: mdi:gauge
      title: Dashboard
      filename: common/ui/ui-lovelace.yaml
      mode: yaml