
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named common/themes

# Text to speech
tts:
  - platform: google_translate

# Bypass login page if localhost
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
      allow_bypass_login: true
    - type: homeassistant

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: storage
  resources:
    - url: /www/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:home
      show_in_sidebar: true
      filename: lovelace.yaml
